### ISSUE TITLE
Ecarts arrêté données essentielles et exemples proposés ici 

### ISSUE THREAD

**Issue by xavieroudin** [etalab/format-commande-publique#28]
Bonjour, 

Nous constatons un écart entre la spécification proposée dans l'arrêté relatif aux données essentielles et les exemples proposés ici en ce qui concerne l'identification des titulaires de marchés publics. 

Dans l'arrêté, la structure est la suivante : titulaires>id
Dans les exemples JSON, il s'agit de titulaires>titulaire>id

Quelle est la bonne spécification à retenir? 

Merci beaucoup

Xavier Oudin
AIFE

**Comment by arisone** [comment]
Bonjour,
Si cela peut être utile, j'ai ouvert le problème #26 pour signaler une erreur dans le fichier d'exemple. Je pense que c'est la même chose.
L'élément `titulaires>titulaire>id` n'est pas conforme au schéma json.
L'élément `titulaires>id` est conforme au schéma json.
J'ai trouvé l'erreur, même vous avez trouvé, seulement dans la modification.


Note: message traduit avec Google Translate

**Comment by ColinMaudry** [comment]
Bonjour,

Le fichier https://github.com/etalab/format-commande-publique/blob/4dfcbbc7c22259dc2db29aefb0b5650adae96a95/exemples/json/mar-avec-modifications.json contient effectivement une erreur.

La bonne spécification en JSON est titulaires > id.

En XML il n'y a pas d'array, un élément "titulaire" est donc utilisé pour chaque titulaire dans "titulaires".

Merci beaucoup pour votre retour.

Colin

-------- Original Message --------

**Comment by xavieroudin** [comment]
Bonjour 

Merci beaucoup pour votre retour. Je clos l'issue. 

xavier
