### ISSUE TITLE
CPV dans les concessions ?

### ISSUE THREAD

**Issue by marion-paclot** [etalab/format-commande-publique#42]
Salut Colin
Est-ce volontaire qu'il n'y ait pas de code CPV dans le schema xsd des contrats de concession ?
Merci

**Comment by ColinMaudry** [comment]
C'est volontaire, dans le sens où le code CPV ne fait pas partie des données requises par le format des données essentielles de concessions : https://www.legifrance.gouv.fr/eli/arrete/2017/4/14/ECFM1637256A/jo/texte#JORFARTI000034492631

**Comment by marion-paclot** [comment]
Donc l'erreur a été commise en amont, au moment de la rédaction de l'arrêté. Dommage...
