### ISSUE TITLE
Envoi de mail lorsqu'une erreur est détectée

### ISSUE THREAD

**Issue by ColinMaudry** [etalab/format-commande-publique#44]
Aujourd'hui, lorsqu'une erreur survient lors du traitement des données DGFiP, nous ne sommes pas informés directement.

L'objectif est que pour chaque étape du traitement, un mail explicite soit envoyé en cas d'erreur.

**Comment by ColinMaudry** [comment]
@abulte À ton avis, on envoie les mails d'erreur sur quelle adresse ? commandepublique@data.gouv.fr ? Il devrait y en a voir un par mois max.

**Comment by abulte** [comment]
Oui ça me parait être la bonne adresse.

**Comment by abulte** [comment]
Sinon, ça serait pas mal si on pouvait se restreindre à utiliser le `MAILTO` du cron plutôt qu'un utilitaire en plus https://www.cyberciti.biz/faq/linux-unix-crontab-change-mailto-settings/.

**Comment by ColinMaudry** [comment]
Et donc cron enverrait un mail à `$MAILTO` si la commande se termine avec `exit 1` ?

**Comment by abulte** [comment]
Oui. Ca peut être plus ou moins sophistiqué en fonction de ce que dit le script et du ce que tu veux dans ton mail, cf ici https://serverfault.com/questions/226074/cron-only-get-errors-in-emails.

**Comment by ColinMaudry** [comment]
C'est OK si on reçoit les messages d'erreur par mail mais qu'on ne les a pas dans les logs ? Je n'arrive par à avoir `stderr` en console et dans les logs.

**Comment by abulte** [comment]
Même avec ça https://serverfault.com/a/942322 ?

**Comment by abulte** [comment]
(dans l'idéal ce serait bien d'avoir les logs et les mails)

**Comment by ColinMaudry** [comment]
Implémenté sur etalab/dgfip-gw (dépôt privé).
